from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from _common import atomic_write_text, load_yaml, yaml_list


OUTPUT_PATH = Path("04_decisions/executive-brief.md")


def _project_path(root: Path, target: str) -> Path:
    if not target.startswith("project/") or target.count("/") != 1:
        raise ValueError("target must be project/<slug>")
    slug = target.split("/", 1)[1]
    projects_root = (root / "projects").resolve()
    project = (projects_root / slug).resolve()
    if project.parent != projects_root or not project.is_dir():
        raise FileNotFoundError(f"project not found: {target}")
    return project


def _collection(project: Path, relative: str, key: str) -> list[dict[str, Any]]:
    path = project / relative
    if not path.exists():
        return []
    return yaml_list(path, key)


def _ordered(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return sorted(records, key=lambda record: str(record.get("id", "")))


def _inline(value: Any) -> str:
    if value is None:
        return "未記録"
    if isinstance(value, list):
        return ", ".join(_inline(item) for item in value) or "なし"
    return " ".join(str(value).splitlines()).strip() or "未記録"


def _labels(ids: list[Any], records: dict[str, dict[str, Any]], label_key: str) -> str:
    labels: list[str] = []
    for record_id in ids:
        if not isinstance(record_id, str):
            continue
        record = records.get(record_id)
        labels.append(f"{record_id}: {_inline(record.get(label_key))}" if record else record_id)
    return "; ".join(labels) or "なし"


def build_executive_brief(root: Path, target: str) -> str:
    project = _project_path(root.resolve(), target)
    manifest = load_yaml(project / "manifest.yaml") or {}
    project_data = manifest.get("project", {}) if isinstance(manifest, dict) else {}
    title = project_data.get("title", target) if isinstance(project_data, dict) else target
    intent_path = project / "00_intake" / "creative-intent.md"
    intent = intent_path.read_text(encoding="utf-8").strip() if intent_path.exists() else ""

    decisions = _ordered(_collection(project, "04_decisions/decision-log.yaml", "decisions"))
    insights = {record.get("id"): record for record in _collection(project, "04_decisions/insight-register.yaml", "insights")}
    rejected = _ordered(_collection(project, "04_decisions/rejected-options.yaml", "rejected_options"))
    uncertainties = _ordered(_collection(project, "04_decisions/uncertainty-register.yaml", "uncertainties"))
    requirements = _ordered(_collection(project, "05_production/production-requirements.yaml", "requirements"))

    rejected_by_id = {record.get("id"): record for record in rejected if isinstance(record.get("id"), str)}
    uncertainty_by_id = {record.get("id"): record for record in uncertainties if isinstance(record.get("id"), str)}

    lines = [
        f"# {_inline(title)} — Executive Brief",
        "",
        "Generated deterministically from canonical project sources. Do not edit this file as source.",
        "",
        "## Creative intent",
        "",
        intent or "未記録",
        "",
        "## Decisions",
        "",
    ]
    if not decisions:
        lines.append("- 未記録")
    for decision in decisions:
        decision_id = _inline(decision.get("id"))
        lines.extend(
            [
                f"### {decision_id}: {_inline(decision.get('question'))}",
                f"- Status: {_inline(decision.get('status'))}",
                f"- Selected option: {_inline(decision.get('selected_option'))}",
                f"- Reason: {_inline(decision.get('reason'))}",
                f"- Insights: {_labels(decision.get('insight_ids', []), insights, 'statement')}",
                f"- Evidence IDs: {_inline(decision.get('evidence_ids', []))}",
                f"- Rejected options: {_labels(decision.get('rejected_option_ids', []), rejected_by_id, 'title') if decision.get('rejected_option_ids') else _inline(decision.get('rejected_options', []))}",
                f"- Uncertainties: {_labels(decision.get('uncertainty_ids', []), uncertainty_by_id, 'statement') if decision.get('uncertainty_ids') else _inline(decision.get('uncertainty'))}",
                f"- Review trigger: {_inline(decision.get('review_trigger'))}",
                "",
            ]
        )

    lines.extend(["## Rejected options", ""])
    if not rejected:
        lines.append("- 未記録")
    for record in rejected:
        lines.extend(
            [
                f"- **{_inline(record.get('id'))}: {_inline(record.get('title'))}**",
                f"  - Reason: {_inline(record.get('reason'))}",
                f"  - Decision IDs: {_inline(record.get('decision_ids', []))}",
            ]
        )

    lines.extend(["", "## Uncertainties", ""])
    if not uncertainties:
        lines.append("- 未記録")
    for record in uncertainties:
        lines.extend(
            [
                f"- **{_inline(record.get('id'))}: {_inline(record.get('statement'))}**",
                f"  - Severity: {_inline(record.get('severity'))}",
                f"  - Decision IDs: {_inline(record.get('decision_ids', []))}",
                f"  - Review trigger: {_inline(record.get('review_trigger'))}",
            ]
        )

    lines.extend(["", "## Production requirements", ""])
    if not requirements:
        lines.append("- 未記録")
    for requirement in requirements:
        lines.append(
            f"- **{_inline(requirement.get('id'))}** [{_inline(requirement.get('priority'))}] "
            f"{_inline(requirement.get('statement'))} (acceptance: {_inline(requirement.get('acceptance_test_ids', []))})"
        )

    return "\n".join(lines).rstrip() + "\n"


def write_executive_brief(root: Path, target: str) -> Path:
    project = _project_path(root.resolve(), target)
    output = project / OUTPUT_PATH
    atomic_write_text(output, build_executive_brief(root, target))
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a deterministic human executive brief from canonical project sources.")
    parser.add_argument("target")
    parser.add_argument("--root", type=Path, required=True, help="temporary work root or external output staging root")
    args = parser.parse_args()
    try:
        print(write_executive_brief(args.root, args.target))
    except (FileNotFoundError, OSError, ValueError) as exc:
        parser.error(str(exc))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
